//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smile___Sunshine_Toy_System.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smile___Sunshine_Toy_System.Properties.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnDelete_Location {
            get {
                object obj = ResourceManager.GetObject("btnDelete.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnDelete_Size {
            get {
                object obj = ResourceManager.GetObject("btnDelete.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnDelete_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnDelete.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Delete Record 的當地語系化字串。
        /// </summary>
        internal static string btnDelete_Text {
            get {
                return ResourceManager.GetString("btnDelete.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnInsert_Location {
            get {
                object obj = ResourceManager.GetObject("btnInsert.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnInsert_Size {
            get {
                object obj = ResourceManager.GetObject("btnInsert.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnInsert_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnInsert.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Insert Record 的當地語系化字串。
        /// </summary>
        internal static string btnInsert_Text {
            get {
                return ResourceManager.GetString("btnInsert.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnReload_BackgroundImage {
            get {
                object obj = ResourceManager.GetObject("btnReload.BackgroundImage", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnReload_BackgroundImageLayout {
            get {
                object obj = ResourceManager.GetObject("btnReload.BackgroundImageLayout", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnReload_Location {
            get {
                object obj = ResourceManager.GetObject("btnReload.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnReload_Size {
            get {
                object obj = ResourceManager.GetObject("btnReload.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnReload_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnReload.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnSearch_Location {
            get {
                object obj = ResourceManager.GetObject("btnSearch.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnSearch_Size {
            get {
                object obj = ResourceManager.GetObject("btnSearch.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnSearch_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnSearch.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Search 的當地語系化字串。
        /// </summary>
        internal static string btnSearch_Text {
            get {
                return ResourceManager.GetString("btnSearch.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnUpdate_Location {
            get {
                object obj = ResourceManager.GetObject("btnUpdate.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnUpdate_Size {
            get {
                object obj = ResourceManager.GetObject("btnUpdate.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object btnUpdate_TabIndex {
            get {
                object obj = ResourceManager.GetObject("btnUpdate.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Update Record 的當地語系化字串。
        /// </summary>
        internal static string btnUpdate_Text {
            get {
                return ResourceManager.GetString("btnUpdate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object cbColumn_Location {
            get {
                object obj = ResourceManager.GetObject("cbColumn.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object cbColumn_Size {
            get {
                object obj = ResourceManager.GetObject("cbColumn.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object cbColumn_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cbColumn.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object cbTable_Location {
            get {
                object obj = ResourceManager.GetObject("cbTable.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object cbTable_Size {
            get {
                object obj = ResourceManager.GetObject("cbTable.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object cbTable_TabIndex {
            get {
                object obj = ResourceManager.GetObject("cbTable.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object gbColumn_Location {
            get {
                object obj = ResourceManager.GetObject("gbColumn.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object gbColumn_Size {
            get {
                object obj = ResourceManager.GetObject("gbColumn.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object gbColumn_TabIndex {
            get {
                object obj = ResourceManager.GetObject("gbColumn.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object gbColumnPanel_Location {
            get {
                object obj = ResourceManager.GetObject("gbColumnPanel.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object gbColumnPanel_Size {
            get {
                object obj = ResourceManager.GetObject("gbColumnPanel.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object gbColumnPanel_TabIndex {
            get {
                object obj = ResourceManager.GetObject("gbColumnPanel.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Column 的當地語系化字串。
        /// </summary>
        internal static string gbColumnPanel_Text {
            get {
                return ResourceManager.GetString("gbColumnPanel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object groupBox1_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object groupBox1_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox1.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object groupBox1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox1.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Table 的當地語系化字串。
        /// </summary>
        internal static string groupBox1_Text {
            get {
                return ResourceManager.GetString("groupBox1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object groupBox2_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox2.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object groupBox2_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox2.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object groupBox2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox2.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Find 的當地語系化字串。
        /// </summary>
        internal static string groupBox2_Text {
            get {
                return ResourceManager.GetString("groupBox2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object groupBox3_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox3.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object groupBox3_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox3.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object groupBox3_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox3.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Control Panel 的當地語系化字串。
        /// </summary>
        internal static string groupBox3_Text {
            get {
                return ResourceManager.GetString("groupBox3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object groupBox5_Location {
            get {
                object obj = ResourceManager.GetObject("groupBox5.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object groupBox5_Size {
            get {
                object obj = ResourceManager.GetObject("groupBox5.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object groupBox5_TabIndex {
            get {
                object obj = ResourceManager.GetObject("groupBox5.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Log 的當地語系化字串。
        /// </summary>
        internal static string groupBox5_Text {
            get {
                return ResourceManager.GetString("groupBox5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object label1_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label1.AutoSize", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object label1_Location {
            get {
                object obj = ResourceManager.GetObject("label1.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object label1_Size {
            get {
                object obj = ResourceManager.GetObject("label1.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object label1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label1.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Column: 的當地語系化字串。
        /// </summary>
        internal static string label1_Text {
            get {
                return ResourceManager.GetString("label1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object label2_AutoSize {
            get {
                object obj = ResourceManager.GetObject("label2.AutoSize", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object label2_Location {
            get {
                object obj = ResourceManager.GetObject("label2.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object label2_Size {
            get {
                object obj = ResourceManager.GetObject("label2.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object label2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("label2.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Value: 的當地語系化字串。
        /// </summary>
        internal static string label2_Text {
            get {
                return ResourceManager.GetString("label2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object lvTable_Location {
            get {
                object obj = ResourceManager.GetObject("lvTable.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object lvTable_Size {
            get {
                object obj = ResourceManager.GetObject("lvTable.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object lvTable_TabIndex {
            get {
                object obj = ResourceManager.GetObject("lvTable.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object rtbDisplay_Location {
            get {
                object obj = ResourceManager.GetObject("rtbDisplay.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object rtbDisplay_ScrollBars {
            get {
                object obj = ResourceManager.GetObject("rtbDisplay.ScrollBars", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object rtbDisplay_Size {
            get {
                object obj = ResourceManager.GetObject("rtbDisplay.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object rtbDisplay_TabIndex {
            get {
                object obj = ResourceManager.GetObject("rtbDisplay.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似  的當地語系化字串。
        /// </summary>
        internal static string rtbDisplay_Text {
            get {
                return ResourceManager.GetString("rtbDisplay.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object tabPage1_Location {
            get {
                object obj = ResourceManager.GetObject("tabPage1.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object tabPage1_Padding {
            get {
                object obj = ResourceManager.GetObject("tabPage1.Padding", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object tabPage1_Size {
            get {
                object obj = ResourceManager.GetObject("tabPage1.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object tabPage1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabPage1.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Record Manage 的當地語系化字串。
        /// </summary>
        internal static string tabPage1_Text {
            get {
                return ResourceManager.GetString("tabPage1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object tabPage2_Location {
            get {
                object obj = ResourceManager.GetObject("tabPage2.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object tabPage2_Padding {
            get {
                object obj = ResourceManager.GetObject("tabPage2.Padding", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object tabPage2_Size {
            get {
                object obj = ResourceManager.GetObject("tabPage2.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object tabPage2_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tabPage2.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Export to PDF 的當地語系化字串。
        /// </summary>
        internal static string tabPage2_Text {
            get {
                return ResourceManager.GetString("tabPage2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object tc1_Location {
            get {
                object obj = ResourceManager.GetObject("tc1.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object tc1_Size {
            get {
                object obj = ResourceManager.GetObject("tc1.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object tc1_TabIndex {
            get {
                object obj = ResourceManager.GetObject("tc1.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object txtValue_Location {
            get {
                object obj = ResourceManager.GetObject("txtValue.Location", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object txtValue_Size {
            get {
                object obj = ResourceManager.GetObject("txtValue.Size", resourceCulture);
                return ((object)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Object 的當地語系化資源。
        /// </summary>
        internal static object txtValue_TabIndex {
            get {
                object obj = ResourceManager.GetObject("txtValue.TabIndex", resourceCulture);
                return ((object)(obj));
            }
        }
    }
}
